import { QuestionItem, UploadedFile } from "@/types/assessment";

export const MOCK_QUESTION_PAPER_FILE: UploadedFile = {
  id: "qp-file-1",
  name: "Class_10_maths_unit_test.pdf",
  sizeFormatted: "2MB",
  sizeBytes: 2 * 1024 * 1024,
  pages: 2,
  type: "question_paper",
  uploadDate: "2026-08-26",
};

export const MOCK_ANSWER_SHEET_FILE: UploadedFile = {
  id: "as-file-1",
  name: "student_1_answer_sheet",
  sizeFormatted: "8MB",
  sizeBytes: 8 * 1024 * 1024,
  pages: 4,
  type: "answer_sheet",
  uploadDate: "2026-08-26",
};

export const REFERENCE_QUESTIONS: QuestionItem[] = [
  {
    id: "q-1",
    questionNumber: 1,
    questionText: "Which blood vessel carries blood away from the heart?",
    maxMarks: 2,
    awardedMarks: 2,
    aiFeedback: "Correct! Arteries carry oxygenated blood away from the heart under high pressure.",
    answerPage: 1,
    boundingBox: {
      id: "bbox-1",
      x: 3,
      y: 4,
      width: 94,
      height: 38,
      label: "Q1",
      page: 1,
    },
  },
  {
    id: "q-2",
    questionNumber: 2,
    questionText: "Which of the following organelles is primarily involved in photosynthesis?",
    maxMarks: 2,
    awardedMarks: 2,
    aiFeedback:
      "Excellent work! You correctly identified the chloroplast as the organelle responsible for photosynthesis. Keep it up!",
    answerPage: 1,
    boundingBox: {
      id: "bbox-2",
      x: 3,
      y: 43,
      width: 94,
      height: 25,
      label: "Q2",
      page: 1,
    },
  },
  {
    id: "q-3",
    questionNumber: 3,
    questionText:
      "Explain the role of chloroplasts in photosynthesis, naming the main pigments involved and briefly outlining the two major stages of the process.",
    maxMarks: 2,
    awardedMarks: 2,
    aiFeedback:
      "Well explained. Chlorophyll a and b pigments noted along with light and dark reaction stages.",
    answerPage: 1,
    boundingBox: {
      id: "bbox-3",
      x: 3,
      y: 70,
      width: 94,
      height: 26,
      label: "Q3",
      page: 1,
    },
  },
  {
    id: "q-4",
    questionNumber: 4,
    questionText:
      "Describe the flow of blood through the human heart starting from the right atrium and ending at the aorta; include the names of valves crossed.",
    maxMarks: 2,
    awardedMarks: 0,
    aiFeedback:
      "Incomplete description. Did not mention tricuspid and bicuspid valve pathways.",
    answerPage: 2,
    boundingBox: {
      id: "bbox-4",
      x: 3,
      y: 8,
      width: 94,
      height: 28,
      label: "Q4",
      page: 2,
    },
  },
  {
    id: "q-5",
    questionNumber: 5,
    questionText:
      "Draw a labelled diagram of an alveolus showing capillaries and air space (label alveolar sac, capillary, and direction of gas exchange).",
    maxMarks: 2,
    awardedMarks: 2,
    aiFeedback: "Neat diagram with all required anatomical labels.",
    answerPage: 2,
    boundingBox: {
      id: "bbox-5",
      x: 3,
      y: 40,
      width: 94,
      height: 48,
      label: "Q5",
      page: 2,
    },
  },
  {
    id: "q-6",
    questionNumber: 6,
    questionText:
      "Draw a neat labelled diagram of the human digestive system (stomach, small intestine, large intestine, liver, pancreas) and label the site where most absorption occurs.",
    maxMarks: 5,
    awardedMarks: 4,
    aiFeedback: "Very good schematic diagram. Missing specific label for ileum villi.",
    answerPage: 3,
    boundingBox: {
      id: "bbox-6",
      x: 3,
      y: 8,
      width: 94,
      height: 50,
      label: "Q6",
      page: 3,
    },
  },
  {
    id: "q-7",
    questionNumber: 7,
    questionText:
      "Draw and label a nephron (Bowman's capsule, glomerulus, proximal tubule, loop of Henle, distal tubule, collecting duct).",
    maxMarks: 5,
    awardedMarks: 5,
    aiFeedback: "Accurate depiction of nephron functional units with correct flow direction.",
    answerPage: 3,
    boundingBox: {
      id: "bbox-7",
      x: 3,
      y: 60,
      width: 94,
      height: 36,
      label: "Q7",
      page: 3,
    },
  },
  {
    id: "q-8",
    questionNumber: 8,
    questionText:
      "Explain the structural differences between palisade mesophyll and spongy mesophyll and state how each structure aids its function in the leaf.",
    maxMarks: 5,
    awardedMarks: 3,
    aiFeedback:
      "Partial credit. Mentioned air spaces in spongy mesophyll but omitted packing density comparison.",
    answerPage: 4,
    boundingBox: {
      id: "bbox-8",
      x: 3,
      y: 10,
      width: 94,
      height: 40,
      label: "Q8",
      page: 4,
    },
  },
  {
    id: "q-9",
    questionNumber: 9,
    questionText:
      "Describe the process of transpiration in plants in two to three sentences and name two environmental factors that increase its rate.",
    maxMarks: 5,
    awardedMarks: 5,
    aiFeedback:
      "Complete and concise answer with temperature and wind speed correctly identified.",
    answerPage: 4,
    boundingBox: {
      id: "bbox-9",
      x: 3,
      y: 52,
      width: 94,
      height: 42,
      label: "Q9",
      page: 4,
    },
  },
  {
    id: "q-10",
    questionNumber: 10,
    questionText:
      "Explain how the structure of xylem vessels facilitates water transport in plants (mention one structural feature and its role).",
    maxMarks: 5,
    awardedMarks: 4,
    aiFeedback: "Lignified cell walls and hollow lumen correctly described.",
    answerPage: 4,
    boundingBox: {
      id: "bbox-10",
      x: 3,
      y: 10,
      width: 94,
      height: 35,
      label: "Q10",
      page: 4,
    },
  },
  {
    id: "q-11a",
    questionNumber: 11,
    subLabel: "a.",
    questionText:
      "A diagram shows two potted plants — Plant A in bright light with broad green leaves, Plant B kept in dim light with pale, elongated leaves.",
    maxMarks: 2,
    awardedMarks: 2,
    aiFeedback: "Etiolation and phototropism factors recognized accurately.",
    answerPage: 4,
    boundingBox: {
      id: "bbox-11a",
      x: 3,
      y: 48,
      width: 94,
      height: 24,
      label: "Q11a",
      page: 4,
    },
  },
  {
    id: "q-11b",
    questionNumber: 11,
    subLabel: "b.",
    questionText: "Suggest one practical measure to help Plant B recover.",
    maxMarks: 3,
    awardedMarks: 1,
    aiFeedback: "Gradual reintroduction to indirect sunlight recommended.",
    answerPage: 4,
    boundingBox: {
      id: "bbox-11b",
      x: 3,
      y: 74,
      width: 94,
      height: 22,
      label: "Q11b",
      page: 4,
    },
  },
  {
    id: "q-12",
    questionNumber: 12,
    questionText:
      "A resting person has tidal volume (air per breath) of 0.5 L and breathes 12 times per minute.",
    maxMarks: 5,
    awardedMarks: 4,
    aiFeedback: "Minute ventilation correctly computed as 6.0 L/min.",
    answerPage: 4,
    boundingBox: {
      id: "bbox-12",
      x: 3,
      y: 10,
      width: 94,
      height: 35,
      label: "Q12",
      page: 4,
    },
  },
  {
    id: "q-13",
    questionNumber: 13,
    questionText:
      "If dead space is 0.15 L per breath, calculate the alveolar ventilation per minute. Show working.",
    maxMarks: 5,
    awardedMarks: 4,
    aiFeedback: "Alveolar ventilation = (0.5 - 0.15) * 12 = 4.2 L/min.",
    answerPage: 4,
    boundingBox: {
      id: "bbox-13",
      x: 3,
      y: 48,
      width: 94,
      height: 48,
      label: "Q13",
      page: 4,
    },
  },
];
